//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5472
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface LoginPort
{
    
    loginResponse login(loginRequest loginRequest);
    
    getUnpackedShellsResponse getUnpackedShells(getUnpackedShellsRequest getUnpackedShellsRequest);
    
    packShellResponse packShell(packShellRequest packShellRequest);
    
    finishShellResponse finishShell(finishShellRequest finishShellRequest);
    
    cancelShellResponse cancelShell(cancelShellRequest cancelShellRequest);
    
    createShellResponse createShell(createShellRequest createShellRequest);
    
    scannedPackage[] finishSession(finishSessionRequest finishSessionRequest);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class loginRequest
{
    
    private string indexField;
    
    private string passwordField;
    
    private string loginField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class loginResponse
{
    
    private string registerIdField;
    
    private string userNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string registerId
    {
        get
        {
            return this.registerIdField;
        }
        set
        {
            this.registerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string userName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class loginRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public loginRequest loginRequest;
    
    public loginRequest1()
    {
    }
    
    public loginRequest1(loginRequest loginRequest)
    {
        this.loginRequest = loginRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class loginResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public loginResponse loginResponse;
    
    public loginResponse1()
    {
    }
    
    public loginResponse1(loginResponse loginResponse)
    {
        this.loginResponse = loginResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class getUnpackedShellsRequest
{
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class getUnpackedShellsResponse
{
    
    private int statusField;
    
    private string[] shellField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shell", Order=1)]
    public string[] shell
    {
        get
        {
            return this.shellField;
        }
        set
        {
            this.shellField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class getUnpackedShellsRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public getUnpackedShellsRequest getUnpackedShellsRequest;
    
    public getUnpackedShellsRequest1()
    {
    }
    
    public getUnpackedShellsRequest1(getUnpackedShellsRequest getUnpackedShellsRequest)
    {
        this.getUnpackedShellsRequest = getUnpackedShellsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class getUnpackedShellsResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public getUnpackedShellsResponse getUnpackedShellsResponse;
    
    public getUnpackedShellsResponse1()
    {
    }
    
    public getUnpackedShellsResponse1(getUnpackedShellsResponse getUnpackedShellsResponse)
    {
        this.getUnpackedShellsResponse = getUnpackedShellsResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class packShellRequest
{
    
    private string indexField;
    
    private string useridField;
    
    private string shellIdField;
    
    private string barcodeIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string userid
    {
        get
        {
            return this.useridField;
        }
        set
        {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string shellId
    {
        get
        {
            return this.shellIdField;
        }
        set
        {
            this.shellIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string barcodeId
    {
        get
        {
            return this.barcodeIdField;
        }
        set
        {
            this.barcodeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class packShellResponse
{
    
    private int statusField;
    
    private int packField;
    
    private int packUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int pack
    {
        get
        {
            return this.packField;
        }
        set
        {
            this.packField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int packUser
    {
        get
        {
            return this.packUserField;
        }
        set
        {
            this.packUserField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class packShellRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public packShellRequest packShellRequest;
    
    public packShellRequest1()
    {
    }
    
    public packShellRequest1(packShellRequest packShellRequest)
    {
        this.packShellRequest = packShellRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class packShellResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public packShellResponse packShellResponse;
    
    public packShellResponse1()
    {
    }
    
    public packShellResponse1(packShellResponse packShellResponse)
    {
        this.packShellResponse = packShellResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class finishShellRequest
{
    
    private string shellField;
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string shell
    {
        get
        {
            return this.shellField;
        }
        set
        {
            this.shellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class finishShellResponse
{
    
    private int statusField;
    
    private int inShellField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int inShell
    {
        get
        {
            return this.inShellField;
        }
        set
        {
            this.inShellField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class finishShellRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public finishShellRequest finishShellRequest;
    
    public finishShellRequest1()
    {
    }
    
    public finishShellRequest1(finishShellRequest finishShellRequest)
    {
        this.finishShellRequest = finishShellRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class finishShellResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public finishShellResponse finishShellResponse;
    
    public finishShellResponse1()
    {
    }
    
    public finishShellResponse1(finishShellResponse finishShellResponse)
    {
        this.finishShellResponse = finishShellResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class cancelShellRequest
{
    
    private string indexField;
    
    private string useridField;
    
    private string shellIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string userid
    {
        get
        {
            return this.useridField;
        }
        set
        {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string shellId
    {
        get
        {
            return this.shellIdField;
        }
        set
        {
            this.shellIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class cancelShellResponse
{
    
    private int cancelField;
    
    private int statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int cancel
    {
        get
        {
            return this.cancelField;
        }
        set
        {
            this.cancelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class cancelShellRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public cancelShellRequest cancelShellRequest;
    
    public cancelShellRequest1()
    {
    }
    
    public cancelShellRequest1(cancelShellRequest cancelShellRequest)
    {
        this.cancelShellRequest = cancelShellRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class cancelShellResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public cancelShellResponse cancelShellResponse;
    
    public cancelShellResponse1()
    {
    }
    
    public cancelShellResponse1(cancelShellResponse cancelShellResponse)
    {
        this.cancelShellResponse = cancelShellResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class createShellRequest
{
    
    private string indexField;
    
    private string useridField;
    
    private string tareNumberField;
    
    private string deliveryIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string userid
    {
        get
        {
            return this.useridField;
        }
        set
        {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string tareNumber
    {
        get
        {
            return this.tareNumberField;
        }
        set
        {
            this.tareNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string deliveryIndex
    {
        get
        {
            return this.deliveryIndexField;
        }
        set
        {
            this.deliveryIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class createShellResponse
{
    
    private int statusField;
    
    private string barcodeShellField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string barcodeShell
    {
        get
        {
            return this.barcodeShellField;
        }
        set
        {
            this.barcodeShellField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class createShellRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public createShellRequest createShellRequest;
    
    public createShellRequest1()
    {
    }
    
    public createShellRequest1(createShellRequest createShellRequest)
    {
        this.createShellRequest = createShellRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class createShellResponse1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public createShellResponse createShellResponse;
    
    public createShellResponse1()
    {
    }
    
    public createShellResponse1(createShellResponse createShellResponse)
    {
        this.createShellResponse = createShellResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class finishSessionRequest
{
    
    private string statusField;
    
    private string operationField;
    
    private string userField;
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string operation
    {
        get
        {
            return this.operationField;
        }
        set
        {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrposhta.ua/motorolla-service")]
public partial class scannedPackage
{
    
    private string unidField;
    
    private int packagesTotalField;
    
    private int packagesScannedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string unid
    {
        get
        {
            return this.unidField;
        }
        set
        {
            this.unidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int packagesTotal
    {
        get
        {
            return this.packagesTotalField;
        }
        set
        {
            this.packagesTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int packagesScanned
    {
        get
        {
            return this.packagesScannedField;
        }
        set
        {
            this.packagesScannedField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class finishSessionRequest1
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public finishSessionRequest finishSessionRequest;
    
    public finishSessionRequest1()
    {
    }
    
    public finishSessionRequest1(finishSessionRequest finishSessionRequest)
    {
        this.finishSessionRequest = finishSessionRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute()]
public partial class finishSessionResponse
{
    
    [System.Xml.Serialization.XmlArrayItemAttribute("scannedPackage", IsNullable=false)]
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://ukrposhta.ua/motorolla-service", Order=0)]
    public scannedPackage[] finishSessionResponse1;
    
    public finishSessionResponse()
    {
    }
    
    public finishSessionResponse(scannedPackage[] finishSessionResponse1)
    {
        this.finishSessionResponse1 = finishSessionResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class LoginPortClient : Microsoft.Tools.ServiceModel.CFClientBase<LoginPort>, LoginPort
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://10.255.102.149:8080/motorolla/");
    
    public LoginPortClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public LoginPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private loginResponse1 login(loginRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        loginResponse1 retVal = base.Invoke<loginRequest1, loginResponse1>(info, request);
        return retVal;
    }
    
    public loginResponse login(loginRequest loginRequest)
    {
        loginRequest1 request = new loginRequest1(loginRequest);
        loginResponse1 response = this.login(request);
        return response.loginResponse;
    }
    
    private getUnpackedShellsResponse1 getUnpackedShells(getUnpackedShellsRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        getUnpackedShellsResponse1 retVal = base.Invoke<getUnpackedShellsRequest1, getUnpackedShellsResponse1>(info, request);
        return retVal;
    }
    
    public getUnpackedShellsResponse getUnpackedShells(getUnpackedShellsRequest getUnpackedShellsRequest)
    {
        getUnpackedShellsRequest1 request = new getUnpackedShellsRequest1(getUnpackedShellsRequest);
        getUnpackedShellsResponse1 response = this.getUnpackedShells(request);
        return response.getUnpackedShellsResponse;
    }
    
    private packShellResponse1 packShell(packShellRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        packShellResponse1 retVal = base.Invoke<packShellRequest1, packShellResponse1>(info, request);
        return retVal;
    }
    
    public packShellResponse packShell(packShellRequest packShellRequest)
    {
        packShellRequest1 request = new packShellRequest1(packShellRequest);
        packShellResponse1 response = this.packShell(request);
        return response.packShellResponse;
    }
    
    private finishShellResponse1 finishShell(finishShellRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        finishShellResponse1 retVal = base.Invoke<finishShellRequest1, finishShellResponse1>(info, request);
        return retVal;
    }
    
    public finishShellResponse finishShell(finishShellRequest finishShellRequest)
    {
        finishShellRequest1 request = new finishShellRequest1(finishShellRequest);
        finishShellResponse1 response = this.finishShell(request);
        return response.finishShellResponse;
    }
    
    private cancelShellResponse1 cancelShell(cancelShellRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        cancelShellResponse1 retVal = base.Invoke<cancelShellRequest1, cancelShellResponse1>(info, request);
        return retVal;
    }
    
    public cancelShellResponse cancelShell(cancelShellRequest cancelShellRequest)
    {
        cancelShellRequest1 request = new cancelShellRequest1(cancelShellRequest);
        cancelShellResponse1 response = this.cancelShell(request);
        return response.cancelShellResponse;
    }
    
    private createShellResponse1 createShell(createShellRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        createShellResponse1 retVal = base.Invoke<createShellRequest1, createShellResponse1>(info, request);
        return retVal;
    }
    
    public createShellResponse createShell(createShellRequest createShellRequest)
    {
        createShellRequest1 request = new createShellRequest1(createShellRequest);
        createShellResponse1 response = this.createShell(request);
        return response.createShellResponse;
    }
    
    private finishSessionResponse finishSession(finishSessionRequest1 request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "";
        info.RequestIsWrapped = false;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = false;
        finishSessionResponse retVal = base.Invoke<finishSessionRequest1, finishSessionResponse>(info, request);
        return retVal;
    }
    
    public scannedPackage[] finishSession(finishSessionRequest finishSessionRequest)
    {
        finishSessionRequest1 request = new finishSessionRequest1(finishSessionRequest);
        finishSessionResponse response = this.finishSession(request);
        return response.finishSessionResponse1;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("", cpr.IncomingSignatureParts, true);
        ApplyProtection("", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
